Update build-rockchip-openwrt-24.10.yml

diff --git a/.github/workflows/build-rockchip-openwrt-24.10.yml b/.github/workflows/build-rockchip-openwrt-24.10.yml
--- a/.github/workflows/build-rockchip-openwrt-24.10.yml
+++ b/.github/workflows/build-rockchip-openwrt-24.10.yml
@@ -35,17 +35,51 @@ on:
 
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
     
     steps:
-      - name: Checkout code
+      - name: Checkout repository
         uses: actions/checkout@v4
-
-      - name: Set executable permissions
-        run: chmod +x ${{ github.workspace }}/rockchip/build.sh
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      
+      - name: Set up OpenWRT build environment
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          apt update
+          apt upgrade
+          apt install apt install build-essential clang flex bison g++ gawk \
+          gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
+          python3-distutils python3-setuptools rsync swig unzip zlib1g-dev file wget
+      
+      - name: Validate PPPoE Inputs
+        run: |
+          if [[ "${{ inputs.enable_pppoe }}" == "yes" ]]; then
+            if [[ -z "${{ inputs.pppoe_account }}" || -z "${{ inputs.pppoe_password }}" ]]; then
+              echo "Error: PPPoE account and password must be provided when PPPoE is enabled!"
+              exit 1
+            fi
+          fi
+      
+      - name: Clone OpenWRT source code
+        run: |
+          git clone https://git.openwrt.org/openwrt/openwrt.git
+          cd openwrt
+      
+      - name: Copy pre-existing .config file
+        run: |
+          cp ${{ github.workspace }}/rockchip/imm.config openwrt/.config
+      
+      - name: Set LAN IP and PPPoE credentials
+        run: |
+          # 修改 network 配置文件中的 LAN IP
+          sed -i "s/option ipaddr '192.168.1.1'/option ipaddr '${{ github.event.inputs.lan_ip }}'/g" files/etc/config/network
+          # 配置 WAN 接口为 PPPoE，并添加用户名和密码
+          sed -i '/config interface "wan"/a\ \ \ \ option proto "pppoe"' files/etc/config/network
+          sed -i "/config interface 'wan'/a\ \ \ \ option username '${{ github.event.inputs.pppoe_username }}'" files/etc/config/network
+          sed -i "/config interface 'wan'/a\ \ \ \ option password '${{ github.event.inputs.pppoe_password }}'" files/etc/config/network
+      
+      - name: Set root filesystem size
+        run: |
+          # 更新 CONFIG_TARGET_ROOTFS_PARTSIZE 配置
+          sed -i "s/^CONFIG_TARGET_ROOTFS_PARTSIZE=.*/CONFIG_TARGET_ROOTFS_PARTSIZE=${{ github.event.inputs.rootfs_size }}/" .config
+      
+      - name: Building Rockchip OpenWrt
+        run: make
